SSH_HOST="10.10.41.221"
SSH_USER="h-bot"
SSH_ALIAS_CONFIG="h-bot.dev"
WEB_DIR=/var/www/h-bot.dev.h-art.it/htdocs/



deploy:
	rsync -rlpcgoDvzi --delete . ${SSH_ALIAS_CONFIG}:${WEB_DIR} --exclude-from 'exclude-list.txt'
	ssh ${SSH_ALIAS_CONFIG} "touch ${WEB_DIR}hbot.wsgi"

build-css:
	sass sass/style.scss static/build/css/style.css
